import holdingHandsIcon from "./holding-hands 1.svg"
import victoryFingersIcon from "./victory-fingers 1.svg"
import checkIcon from "./check 1.svg"
import phoneIcon from "./phone.svg"
import mailIcon from "./mail.svg"
import locationIcon from "./location.svg"
import facebookIcon from "./facebook.svg"
import instagramIcon from "./instagram.svg"
import logoLightLarge from "./logo_light_large.png"
import banner from "./banner.jpg"
import galleryImage1 from "./gallery-image 1.jpg"
import galleryImage2 from "./gallery-image 2.jpg"
import galleryImage3 from "./gallery-image 3.jpg"
import galleryImage4 from "./gallery-image 4.jpg"
import galleryImage5 from "./gallery-image 5.jpg"
import galleryImage6 from "./gallery-image 6.jpg"
import logoDark from "./logo_dark.png"
import logoLight from "./logo_light.png"
import menuIcon from "./menu.svg"
import closeIcon from "./close.svg"
import homeIcon from "./home.svg"
import aboutIcon from "./about.svg"
import planeIcon from "./plane.svg"
import categoriesImage1 from "./categories-image-1.jpg"
import clockIcon from "./clock.svg"
import tourPreview1 from "./tour-preview-1.jpg"
import arrowRightIcon from "./arrow-right.svg"

export { holdingHandsIcon, victoryFingersIcon, checkIcon, phoneIcon, mailIcon, locationIcon, facebookIcon, instagramIcon, logoLightLarge,
banner, galleryImage1, galleryImage2, galleryImage3, galleryImage4, galleryImage5, galleryImage6, logoDark, logoLight, menuIcon,
closeIcon, homeIcon, aboutIcon, planeIcon, categoriesImage1, clockIcon, tourPreview1, arrowRightIcon }