import holdingHandsIcon from "./holding-hands 1.svg"
import victoryFingersIcon from "./victory-fingers 1.svg"
import checkIcon from "./check 1.svg"
import phoneIcon from "./phone.svg"
import mailIcon from "./mail.svg"
import locationIcon from "./location.svg"
import facebookIcon from "./facebook.svg"
import instagramIcon from "./instagram.svg"
import logoLightLarge from "./logo_light_large.png"
import banner from "./banner.jpg"
import galleryImage1 from "./gallery-image 1.jpg"
import galleryImage2 from "./gallery-image 2.jpg"
import galleryImage3 from "./gallery-image 3.jpg"
import galleryImage4 from "./gallery-image 4.jpg"
import galleryImage5 from "./gallery-image 5.jpg"
import galleryImage6 from "./gallery-image 6.jpg"
import logoDark from "./logo_dark.png"
import logoLight from "./logo_light.png"
import menuIcon from "./menu.svg"
import closeIcon from "./close.svg"
import homeIcon from "./home.svg"
import aboutIcon from "./about.svg"
import planeIcon from "./plane.svg"
import clockIcon from "./clock.svg"
import tourPreview1 from "./tour-preview-1.jpg"
import arrowRightIcon from "./arrow-right.svg"
import heroPrivate from "./hero-private.png"
import themeImage1 from "./theme-image-1.jpg"
import themeImage2 from "./theme-image-2.jpg"
import themeImage3 from "./theme-image-3.jpg"
import themeImage4 from "./theme-image-4.jpg"
import themeImage5 from "./theme-image-5.jpg"
import themeImage6 from "./theme-image-6.jpg"
import categoriesImage1 from "./halongbay-small.jpg"
import categoriesImage2 from "./trangan-small.jpg"
import categoriesImage3 from "./themetour-small.jpg"
import categoriesImage4 from "./bridge-small.jpg"
import arrowDown from "./arrow-down.svg"
import infoIcon from "./info.svg"
import rollingAnimation from "./Rolling-0.9s-197px.svg"
import playIcon from "./play.svg"
import glassIcon from "./glass.svg"
import globeIcon from "./globe.svg"

export { holdingHandsIcon, victoryFingersIcon, checkIcon, phoneIcon, mailIcon, locationIcon, facebookIcon, instagramIcon, logoLightLarge,
banner, galleryImage1, galleryImage2, galleryImage3, galleryImage4, galleryImage5, galleryImage6, logoDark, logoLight, menuIcon,
closeIcon, homeIcon, aboutIcon, planeIcon, categoriesImage1, categoriesImage2, categoriesImage3, categoriesImage4, clockIcon, tourPreview1, 
arrowRightIcon, heroPrivate, themeImage1, themeImage2, themeImage3, themeImage4, themeImage5, themeImage6, arrowDown, infoIcon, rollingAnimation,
playIcon, glassIcon, globeIcon }
